version: 2

jobs:
  build:
    docker:
      - image: docker:stable-git
  install-dependencies:
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: |
          yarn install
  lint-and-flow:
      steps:
        - attach_workspace:
            at: ~/project
        - run: |
            yarn prettier
