version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/project

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: |
          yarn install
  lint-and-flow:
    <<: *defaults
      steps:
        - attach_workspace:
            at: ~/project
        - run: |
            yarn prettier

workflows:
  version: 2

  build-and-test:
    jobs:
      - install-dependencies
      - lint-and-flow:
          requires:
            - install-dependencies