version: 2

jobs:
  install-dependencies:
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run: |
          yarn install
  lint-and-flow:
      steps:
        - attach_workspace:
            at: ~/project
        - run: |
            yarn prettier

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint-and-flow:
          requires:
            - install-dependencies